/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_mainWindow (void)
{
  GtkWidget *mainWindow;
  GtkWidget *scrolledwindow1;
  GtkWidget *viewport1;
  GtkWidget *mainVBox;
  GtkWidget *connectionFrame;
  GtkWidget *vbox4;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *serialconnframe;
  GtkWidget *hbox2;
  GtkWidget *serialDeviceEntry;
  GtkWidget *label2;
  GtkWidget *netconframe;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *remoteHostEntry;
  GtkObject *remoteHostPort_adj;
  GtkWidget *remoteHostPort;
  GtkWidget *label3;
  GtkWidget *hbox5;
  GtkWidget *useSerialLink;
  GtkWidget *label1;
  GtkWidget *hseparator1;
  GtkWidget *IdentFrame;
  GtkWidget *alignment4;
  GtkWidget *identTable;
  GtkWidget *sensorIDEntry;
  GtkWidget *sensorPasswordEntry;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *dataServerIP;
  GtkWidget *dataServerHost;
  GtkWidget *label4;
  GtkWidget *networkFrame;
  GtkWidget *alignment5;
  GtkWidget *networkTable;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *labelessid;
  GtkWidget *label13;
  GtkWidget *sensorIPEntry;
  GtkWidget *netmaskEntry;
  GtkWidget *gatewayEntry;
  GtkWidget *essidEntry;
  GtkWidget *wirelessKeyEntry;
  GtkWidget *label9;
  GtkWidget *dhcpCheckbox;
  GtkWidget *label14;
  GtkWidget *networkTypeCombo;
  GtkWidget *label18;
  GtkWidget *label5;
  GtkWidget *MasterKeyFrame;
  GtkWidget *alignment6;
  GtkWidget *hbox4;
  GtkWidget *label15;
  GtkWidget *masterKeyEntry;
  GtkWidget *label6;
  GtkWidget *UpdateFrame;
  GtkWidget *alignment7;
  GtkWidget *vbox5;
  GtkWidget *sensorImportButton;
  GtkWidget *sensorUpdateButton;
  GtkWidget *label16;

  mainWindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (mainWindow), "Configurator");
  gtk_window_set_position (GTK_WINDOW (mainWindow), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (mainWindow), 400, 500);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_container_add (GTK_CONTAINER (mainWindow), scrolledwindow1);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), viewport1);

  mainVBox = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (mainVBox);
  gtk_container_add (GTK_CONTAINER (viewport1), mainVBox);

  connectionFrame = gtk_frame_new (NULL);
  gtk_widget_show (connectionFrame);
  gtk_box_pack_start (GTK_BOX (mainVBox), connectionFrame, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (connectionFrame), GTK_SHADOW_NONE);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (connectionFrame), vbox4);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1);
  gtk_box_pack_start (GTK_BOX (vbox4), alignment1, TRUE, TRUE, 0);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment1), 0, 0, 12, 0);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  serialconnframe = gtk_frame_new (NULL);
  gtk_widget_show (serialconnframe);
  gtk_box_pack_start (GTK_BOX (hbox1), serialconnframe, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (serialconnframe), GTK_SHADOW_NONE);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (serialconnframe), hbox2);

  serialDeviceEntry = gtk_entry_new ();
  gtk_widget_show (serialDeviceEntry);
  gtk_box_pack_start (GTK_BOX (hbox2), serialDeviceEntry, TRUE, TRUE, 0);
  gtk_entry_set_text (GTK_ENTRY (serialDeviceEntry), "/dev/ttyACM0");
  gtk_entry_set_invisible_char (GTK_ENTRY (serialDeviceEntry), 9679);

  label2 = gtk_label_new ("<b>Serial connection</b>");
  gtk_widget_show (label2);
  gtk_frame_set_label_widget (GTK_FRAME (serialconnframe), label2);
  gtk_label_set_use_markup (GTK_LABEL (label2), TRUE);

  netconframe = gtk_frame_new (NULL);
  gtk_widget_show (netconframe);
  gtk_box_pack_start (GTK_BOX (hbox1), netconframe, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (netconframe), GTK_SHADOW_NONE);

  alignment3 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (netconframe), alignment3);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment3), 0, 0, 12, 0);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  remoteHostEntry = gtk_entry_new ();
  gtk_widget_show (remoteHostEntry);
  gtk_box_pack_start (GTK_BOX (hbox3), remoteHostEntry, TRUE, TRUE, 0);
  gtk_entry_set_text (GTK_ENTRY (remoteHostEntry), "192.168.0.2");
  gtk_entry_set_invisible_char (GTK_ENTRY (remoteHostEntry), 9679);

  remoteHostPort_adj = gtk_adjustment_new (80, 1, 65665, 1, 10, 0);
  remoteHostPort = gtk_spin_button_new (GTK_ADJUSTMENT (remoteHostPort_adj), 1, 0);
  gtk_widget_show (remoteHostPort);
  gtk_box_pack_start (GTK_BOX (hbox3), remoteHostPort, TRUE, TRUE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (remoteHostPort), TRUE);
  gtk_spin_button_set_update_policy (GTK_SPIN_BUTTON (remoteHostPort), GTK_UPDATE_IF_VALID);

  label3 = gtk_label_new ("<b>Network connection</b>");
  gtk_widget_show (label3);
  gtk_frame_set_label_widget (GTK_FRAME (netconframe), label3);
  gtk_label_set_use_markup (GTK_LABEL (label3), TRUE);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox5, TRUE, TRUE, 0);

  useSerialLink = gtk_check_button_new_with_mnemonic ("Use the serial link to connect to the sensor");
  gtk_widget_show (useSerialLink);
  gtk_box_pack_start (GTK_BOX (hbox5), useSerialLink, FALSE, FALSE, 0);

  label1 = gtk_label_new ("<b>Connection type</b>");
  gtk_widget_show (label1);
  gtk_frame_set_label_widget (GTK_FRAME (connectionFrame), label1);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (mainVBox), hseparator1, TRUE, TRUE, 0);

  IdentFrame = gtk_frame_new (NULL);
  gtk_widget_show (IdentFrame);
  gtk_box_pack_start (GTK_BOX (mainVBox), IdentFrame, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (IdentFrame), GTK_SHADOW_NONE);

  alignment4 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (IdentFrame), alignment4);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment4), 0, 0, 12, 0);

  identTable = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (identTable);
  gtk_container_add (GTK_CONTAINER (alignment4), identTable);

  sensorIDEntry = gtk_entry_new ();
  gtk_widget_show (sensorIDEntry);
  gtk_table_attach (GTK_TABLE (identTable), sensorIDEntry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (sensorIDEntry), 9679);

  sensorPasswordEntry = gtk_entry_new ();
  gtk_widget_show (sensorPasswordEntry);
  gtk_table_attach (GTK_TABLE (identTable), sensorPasswordEntry, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_visibility (GTK_ENTRY (sensorPasswordEntry), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (sensorPasswordEntry), 9679);

  label7 = gtk_label_new ("Sensor ID");
  gtk_widget_show (label7);
  gtk_table_attach (GTK_TABLE (identTable), label7, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label7), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label7), 10, 0);

  label8 = gtk_label_new ("Sensor password");
  gtk_widget_show (label8);
  gtk_table_attach (GTK_TABLE (identTable), label8, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label8), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label8), 10, 0);

  label19 = gtk_label_new ("Data server's IP");
  gtk_widget_show (label19);
  gtk_table_attach (GTK_TABLE (identTable), label19, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label19), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label19), 10, 0);

  label20 = gtk_label_new ("Data server's hostname");
  gtk_widget_show (label20);
  gtk_table_attach (GTK_TABLE (identTable), label20, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label20), 0, 0.49);
  gtk_misc_set_padding (GTK_MISC (label20), 10, 0);

  dataServerIP = gtk_entry_new ();
  gtk_widget_show (dataServerIP);
  gtk_table_attach (GTK_TABLE (identTable), dataServerIP, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (dataServerIP), 9679);

  dataServerHost = gtk_entry_new ();
  gtk_widget_show (dataServerHost);
  gtk_table_attach (GTK_TABLE (identTable), dataServerHost, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (dataServerHost), 9679);

  label4 = gtk_label_new ("<b>Sensor Identification</b>");
  gtk_widget_show (label4);
  gtk_frame_set_label_widget (GTK_FRAME (IdentFrame), label4);
  gtk_label_set_use_markup (GTK_LABEL (label4), TRUE);

  networkFrame = gtk_frame_new (NULL);
  gtk_widget_show (networkFrame);
  gtk_box_pack_start (GTK_BOX (mainVBox), networkFrame, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (networkFrame), GTK_SHADOW_NONE);

  alignment5 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (networkFrame), alignment5);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment5), 0, 0, 12, 0);

  networkTable = gtk_table_new (7, 2, FALSE);
  gtk_widget_show (networkTable);
  gtk_container_add (GTK_CONTAINER (alignment5), networkTable);

  label10 = gtk_label_new ("Network mask");
  gtk_widget_show (label10);
  gtk_table_attach (GTK_TABLE (networkTable), label10, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label10), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label10), 10, 0);

  label11 = gtk_label_new ("Gateway address");
  gtk_widget_show (label11);
  gtk_table_attach (GTK_TABLE (networkTable), label11, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label11), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label11), 10, 0);

  labelessid = gtk_label_new ("Wireless ESSID");
  gtk_widget_show (labelessid);
  gtk_table_attach (GTK_TABLE (networkTable), labelessid, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (labelessid), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (labelessid), 10, 0);

  label13 = gtk_label_new ("Wireless key");
  gtk_widget_show (label13);
  gtk_table_attach (GTK_TABLE (networkTable), label13, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label13), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label13), 10, 0);

  sensorIPEntry = gtk_entry_new ();
  gtk_widget_show (sensorIPEntry);
  gtk_table_attach (GTK_TABLE (networkTable), sensorIPEntry, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (sensorIPEntry), 9679);

  netmaskEntry = gtk_entry_new ();
  gtk_widget_show (netmaskEntry);
  gtk_table_attach (GTK_TABLE (networkTable), netmaskEntry, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (netmaskEntry), 9679);

  gatewayEntry = gtk_entry_new ();
  gtk_widget_show (gatewayEntry);
  gtk_table_attach (GTK_TABLE (networkTable), gatewayEntry, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (gatewayEntry), 9679);

  essidEntry = gtk_entry_new ();
  gtk_widget_show (essidEntry);
  gtk_table_attach (GTK_TABLE (networkTable), essidEntry, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (essidEntry), 9679);

  wirelessKeyEntry = gtk_entry_new ();
  gtk_widget_show (wirelessKeyEntry);
  gtk_table_attach (GTK_TABLE (networkTable), wirelessKeyEntry, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (wirelessKeyEntry), 9679);

  label9 = gtk_label_new ("Sensor IP Address");
  gtk_widget_show (label9);
  gtk_table_attach (GTK_TABLE (networkTable), label9, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 3);
  gtk_misc_set_alignment (GTK_MISC (label9), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label9), 10, 0);

  dhcpCheckbox = gtk_check_button_new_with_mnemonic ("Use DHCP ?");
  gtk_widget_show (dhcpCheckbox);
  gtk_table_attach (GTK_TABLE (networkTable), dhcpCheckbox, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label14 = gtk_label_new ("If DHCP is used you don't\nneed to fill the fields bellow");
  gtk_widget_show (label14);
  gtk_table_attach (GTK_TABLE (networkTable), label14, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label14), 0, 0.5);

  networkTypeCombo = gtk_combo_box_new_text ();
  gtk_widget_show (networkTypeCombo);
  gtk_table_attach (GTK_TABLE (networkTable), networkTypeCombo, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (networkTypeCombo), "AUTO");
  gtk_combo_box_append_text (GTK_COMBO_BOX (networkTypeCombo), "OPEN");
  gtk_combo_box_append_text (GTK_COMBO_BOX (networkTypeCombo), "WEP");
  gtk_combo_box_append_text (GTK_COMBO_BOX (networkTypeCombo), "WPA-PSK");
  gtk_combo_box_append_text (GTK_COMBO_BOX (networkTypeCombo), "WPA2-PSK");

  label18 = gtk_label_new ("Network security");
  gtk_widget_show (label18);
  gtk_table_attach (GTK_TABLE (networkTable), label18, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label18), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label18), 10, 0);

  label5 = gtk_label_new ("<b>Network configuration</b>");
  gtk_widget_show (label5);
  gtk_frame_set_label_widget (GTK_FRAME (networkFrame), label5);
  gtk_label_set_use_markup (GTK_LABEL (label5), TRUE);

  MasterKeyFrame = gtk_frame_new (NULL);
  gtk_widget_show (MasterKeyFrame);
  gtk_box_pack_start (GTK_BOX (mainVBox), MasterKeyFrame, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (MasterKeyFrame), GTK_SHADOW_NONE);

  alignment6 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (MasterKeyFrame), alignment6);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment6), 0, 0, 12, 0);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox4);

  label15 = gtk_label_new ("Master key ");
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox4), label15, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label15), 10, 0);

  masterKeyEntry = gtk_entry_new ();
  gtk_widget_show (masterKeyEntry);
  gtk_box_pack_start (GTK_BOX (hbox4), masterKeyEntry, TRUE, TRUE, 0);
  gtk_entry_set_visibility (GTK_ENTRY (masterKeyEntry), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (masterKeyEntry), 9679);

  label6 = gtk_label_new ("<b>Master key</b>");
  gtk_widget_show (label6);
  gtk_frame_set_label_widget (GTK_FRAME (MasterKeyFrame), label6);
  gtk_label_set_use_markup (GTK_LABEL (label6), TRUE);

  UpdateFrame = gtk_frame_new (NULL);
  gtk_widget_show (UpdateFrame);
  gtk_box_pack_start (GTK_BOX (mainVBox), UpdateFrame, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (UpdateFrame), GTK_SHADOW_NONE);

  alignment7 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (UpdateFrame), alignment7);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment7), 0, 0, 12, 0);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox5);
  gtk_container_add (GTK_CONTAINER (alignment7), vbox5);

  sensorImportButton = gtk_button_new_with_mnemonic ("Connect to the sensor and download the configuration");
  gtk_widget_show (sensorImportButton);
  gtk_box_pack_start (GTK_BOX (vbox5), sensorImportButton, FALSE, FALSE, 0);

  sensorUpdateButton = gtk_button_new_with_mnemonic ("Connect to the sensor and update the configuration");
  gtk_widget_show (sensorUpdateButton);
  gtk_box_pack_start (GTK_BOX (vbox5), sensorUpdateButton, FALSE, FALSE, 0);

  label16 = gtk_label_new ("<b>Update the sensor !</b>");
  gtk_widget_show (label16);
  gtk_frame_set_label_widget (GTK_FRAME (UpdateFrame), label16);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mainWindow, mainWindow, "mainWindow");
  GLADE_HOOKUP_OBJECT (mainWindow, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (mainWindow, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (mainWindow, mainVBox, "mainVBox");
  GLADE_HOOKUP_OBJECT (mainWindow, connectionFrame, "connectionFrame");
  GLADE_HOOKUP_OBJECT (mainWindow, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (mainWindow, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (mainWindow, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (mainWindow, serialconnframe, "serialconnframe");
  GLADE_HOOKUP_OBJECT (mainWindow, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (mainWindow, serialDeviceEntry, "serialDeviceEntry");
  GLADE_HOOKUP_OBJECT (mainWindow, label2, "label2");
  GLADE_HOOKUP_OBJECT (mainWindow, netconframe, "netconframe");
  GLADE_HOOKUP_OBJECT (mainWindow, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (mainWindow, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (mainWindow, remoteHostEntry, "remoteHostEntry");
  GLADE_HOOKUP_OBJECT (mainWindow, remoteHostPort, "remoteHostPort");
  GLADE_HOOKUP_OBJECT (mainWindow, label3, "label3");
  GLADE_HOOKUP_OBJECT (mainWindow, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (mainWindow, useSerialLink, "useSerialLink");
  GLADE_HOOKUP_OBJECT (mainWindow, label1, "label1");
  GLADE_HOOKUP_OBJECT (mainWindow, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (mainWindow, IdentFrame, "IdentFrame");
  GLADE_HOOKUP_OBJECT (mainWindow, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (mainWindow, identTable, "identTable");
  GLADE_HOOKUP_OBJECT (mainWindow, sensorIDEntry, "sensorIDEntry");
  GLADE_HOOKUP_OBJECT (mainWindow, sensorPasswordEntry, "sensorPasswordEntry");
  GLADE_HOOKUP_OBJECT (mainWindow, label7, "label7");
  GLADE_HOOKUP_OBJECT (mainWindow, label8, "label8");
  GLADE_HOOKUP_OBJECT (mainWindow, label19, "label19");
  GLADE_HOOKUP_OBJECT (mainWindow, label20, "label20");
  GLADE_HOOKUP_OBJECT (mainWindow, dataServerIP, "dataServerIP");
  GLADE_HOOKUP_OBJECT (mainWindow, dataServerHost, "dataServerHost");
  GLADE_HOOKUP_OBJECT (mainWindow, label4, "label4");
  GLADE_HOOKUP_OBJECT (mainWindow, networkFrame, "networkFrame");
  GLADE_HOOKUP_OBJECT (mainWindow, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (mainWindow, networkTable, "networkTable");
  GLADE_HOOKUP_OBJECT (mainWindow, label10, "label10");
  GLADE_HOOKUP_OBJECT (mainWindow, label11, "label11");
  GLADE_HOOKUP_OBJECT (mainWindow, labelessid, "labelessid");
  GLADE_HOOKUP_OBJECT (mainWindow, label13, "label13");
  GLADE_HOOKUP_OBJECT (mainWindow, sensorIPEntry, "sensorIPEntry");
  GLADE_HOOKUP_OBJECT (mainWindow, netmaskEntry, "netmaskEntry");
  GLADE_HOOKUP_OBJECT (mainWindow, gatewayEntry, "gatewayEntry");
  GLADE_HOOKUP_OBJECT (mainWindow, essidEntry, "essidEntry");
  GLADE_HOOKUP_OBJECT (mainWindow, wirelessKeyEntry, "wirelessKeyEntry");
  GLADE_HOOKUP_OBJECT (mainWindow, label9, "label9");
  GLADE_HOOKUP_OBJECT (mainWindow, dhcpCheckbox, "dhcpCheckbox");
  GLADE_HOOKUP_OBJECT (mainWindow, label14, "label14");
  GLADE_HOOKUP_OBJECT (mainWindow, networkTypeCombo, "networkTypeCombo");
  GLADE_HOOKUP_OBJECT (mainWindow, label18, "label18");
  GLADE_HOOKUP_OBJECT (mainWindow, label5, "label5");
  GLADE_HOOKUP_OBJECT (mainWindow, MasterKeyFrame, "MasterKeyFrame");
  GLADE_HOOKUP_OBJECT (mainWindow, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (mainWindow, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (mainWindow, label15, "label15");
  GLADE_HOOKUP_OBJECT (mainWindow, masterKeyEntry, "masterKeyEntry");
  GLADE_HOOKUP_OBJECT (mainWindow, label6, "label6");
  GLADE_HOOKUP_OBJECT (mainWindow, UpdateFrame, "UpdateFrame");
  GLADE_HOOKUP_OBJECT (mainWindow, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (mainWindow, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (mainWindow, sensorImportButton, "sensorImportButton");
  GLADE_HOOKUP_OBJECT (mainWindow, sensorUpdateButton, "sensorUpdateButton");
  GLADE_HOOKUP_OBJECT (mainWindow, label16, "label16");

  return mainWindow;
}

